// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzOPoASfZ0SXk5vqmhxy16cpyGDzzKm9g',
    appId: '1:250423593022:web:78f920c35162b11b98e96f',
    messagingSenderId: '250423593022',
    projectId: 'app-baber-f3e48',
    authDomain: 'app-baber-f3e48.firebaseapp.com',
    storageBucket: 'app-baber-f3e48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIffq2mO5O1KHwGC978kDrgfD4DPr93OA',
    appId: '1:250423593022:android:044813a937e69a9098e96f',
    messagingSenderId: '250423593022',
    projectId: 'app-baber-f3e48',
    storageBucket: 'app-baber-f3e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoV3959fQA0g5Qmf-MzgvoEstA0tFXtJc',
    appId: '1:250423593022:ios:1e27248447d791a098e96f',
    messagingSenderId: '250423593022',
    projectId: 'app-baber-f3e48',
    storageBucket: 'app-baber-f3e48.firebasestorage.app',
    iosClientId: '250423593022-fncd8h0p32t1vaiftvbrg6c6nu1vdiq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoV3959fQA0g5Qmf-MzgvoEstA0tFXtJc',
    appId: '1:250423593022:ios:1e27248447d791a098e96f',
    messagingSenderId: '250423593022',
    projectId: 'app-baber-f3e48',
    storageBucket: 'app-baber-f3e48.firebasestorage.app',
    iosClientId: '250423593022-fncd8h0p32t1vaiftvbrg6c6nu1vdiq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzOPoASfZ0SXk5vqmhxy16cpyGDzzKm9g',
    appId: '1:250423593022:web:62bc79787889592d98e96f',
    messagingSenderId: '250423593022',
    projectId: 'app-baber-f3e48',
    authDomain: 'app-baber-f3e48.firebaseapp.com',
    storageBucket: 'app-baber-f3e48.firebasestorage.app',
  );

}